#
#  Makefile for GXemul src/console
#
#  This directory contains code that is related to console and framebuffer
#  handling.
#

CFLAGS=$(CWARNINGS) $(COPTIM) $(XINCLUDE) $(SDLINCLUDE) $(DINCLUDE)

OBJS=display.o x11.o sdl.o

all: $(OBJS)

$(OBJS): Makefile


clean:
	rm -f $(OBJS) *core

clean_all: clean
	rm -f Makefile
